# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Darren Wong
url:              
paginate:         1
baseurl:          /weblog
author:
  name:           Darren Wong
  url:            darrendavenwong.com
  email:          darrendavenwong@gmail.com

# Custom vars
#version:          1.0.0
#github:
# repo:           https://github.com/poole/poole
